#!/bin/sh

cat << EOF
----------------------------------------------------
  ____            _                            _   
 |  _ \ _ __ ___ | |_ ___  _ __ _ __ ___ _ __ | |_ 
 | |_) | '__/ _ \| __/ _ \| '__| '__/ _ \ '_ \| __|
 |  __/| | | (_) | || (_) | |  | | |  __/ | | | |_ 
 |_|   |_|  \___/ \__\___/|_|  |_|  \___|_| |_|\__|

              Updated by ♟️ resech
____________________________________________________   
🔧 Need help? https://github.com/resech/protorrent
🐛 Bug? https://github.com/resech/protorrent/issues/new
----------------------------------------------------
$(uname -a)
$(wg --version)
$(iptables --version)
$(qbittorrent-nox --version)
User UID: $(id -u abc)
User GID: $(id -g abc)
----------------------------------------------------
EOF
