name: Trivy Vulnerablility Scan
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate tarball from image
      run: |
        docker pull ghcr.io/resech/protorrent:main
        docker save -o vuln-image.tar ghcr.io/resech/protorrent:main

    - name: Run Trivy vulnerability scanner in tarball mode
      uses: aquasecurity/trivy-action@0.28.0
      with:
        input: /github/workspace/vuln-image.tar
        severity: 'CRITICAL,HIGH,MEDIUM'